env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
gemfile:
  - gemfiles/activesupport3.rb
  - gemfiles/activesupport4.rb
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby-19mode
  - jruby-head
  - rbx
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
  fast_finish: true
sudo: false
